server:
  port: 8080
  servlet:
    session:
      timeout: 600s

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #[databasename]为数据库名，记得修改,例如jwxt
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
      username: root
      password: 1234

